### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by brax10ward** [erickzanardo/dashbook#20]
👋 Thanks for creating this package. So far it has been super easy and quick to get it running on the few widgets I have created for my project.

I am new to flutter/dart so forgive the beginner question. 

I am wondering if there is a way to setup the file structure so that not all the chapters have to be in the same class?

**Comment by erickzanardo** [comment]
Hey, there is probably multiple answers to this question as there is no specific folder structure that needs to be used in order to use Dashbook.

The structure that I like to use when having a high number of stories or chapters is the following:

```
  stories/
     - button/button_story.dart
     - main.dart
```

Then on the `button_story.dart` I would expose a function that receives the Dashbook instance and adds all the stories on it and the `main.dart` would build the Dashbook instance and calls the functions.

Let me know if this is clear.

Since this is not an issue, I am gonna close this. But feel free to add additional comments with more question if needed.
